CREATE TABLE IF NOT EXISTS LH_00CIF_D_POPNEXT_DT (
PID STRING COMMENT 'pid' ,
OPNPROV STRING COMMENT '注册省市代码' ,
OPNBK STRING COMMENT '注册机构' ,
NEWFIELDDATE STRING COMMENT '新增日期' ) COMMENT '个人注册信息表' LIFECYCLE 365 hiddenChannel